# -*- coding:UTF-8 -*-
"""
Django settings for DjangoDemo01 project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# os.path.dirname 项目文件的绝对路径
# os.path.abspath(__file__)当前文件的绝对路径
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 密钥
SECRET_KEY = 'gn@m6=nytk*_=frx^yxh!1%9j7$oi3cv=9d1q3r0vpoe6p0d!3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 设置允许访问到本项目的地址列表
# 如果为空的话,则只能通过本机访问
# 如果允许被外部机器访问的话,此处改为["*"]并配合着./manage.py runserver 0.0.0.0:8000的方式进行启动
ALLOWED_HOSTS = ["*"]


# Application definition
# 注册django中的应用(需要先创建再注册再使用)
INSTALLED_APPS = [
    # 'django.contrib.sites',
    # 'registration',  # should be immidiately above "django.contrib.admin"
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
]
# ACCOUNT_ACTIVATION_DAYS =7 # One-week activation window; you may, of course, use a different value.

# 中间件,自定义的中间件的类需要在此注册
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

# 指定项目的主路由配置文件
ROOT_URLCONF = 'project_xianyu.urls'

TEMPLATES = [
    {
        # 指定使用模板的引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 指定存放模板的文件夹
        # os.path.join(BASE_DIR, 'templates')将所有模板都保存在项目中的templates目录中
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 指定是否要搜索应用(app)中的模板目录(True 为搜索)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_xianyu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# 数据库配置信息
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xianyudb',
        'USER': 'root',
        'PASSWORD':"password",
        'HOST':"localhost",
        'PORT':3306

    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
# 语言设置,如果需要将项目变成中文的,需要将 LANGUAGE_CODE 改为zh-Hans
LANGUAGE_CODE = 'en-us'

# 指定时区,则将值修改为Asia/Shanghai   'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# 静态文件的访问路径
STATIC_URL = '/static/'

# 静态文件的存储路径
STATICFILES_DIRS = (
        os.path.join(BASE_DIR,"static"),)

# 设置session的有效期:
SESSION_EXPIRE_AT_BROWER_CLOSE = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = False   #是否使用TLS安全传输协议(用于在两个通信应用程序之间提供保密性和数据完整性。)
EMAIL_USE_SSL = True    #是否使用SSL加密，qq企业邮箱要求使用
EMAIL_HOST = 'smtp.163.com'   #发送邮件的邮箱 的 SMTP服务器，这里用了163邮箱
EMAIL_PORT = 465     #发件箱的SMTP服务器端口
EMAIL_HOST_USER = 'sheepsleep2016@163.com'    #发送邮件的邮箱地址
EMAIL_HOST_PASSWORD = 'q1a2z3'         #发送邮件的邮箱密码(这里使用的是授权码)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = False   #是否使用TLS安全传输协议(用于在两个通信应用程序之间提供保密性和数据完整性。)
# EMAIL_USE_SSL = True    #是否使用SSL加密，qq企业邮箱要求使用
# EMAIL_HOST = 'smtp.qq.com'   #发送邮件的邮箱 的 SMTP服务器，这里用了163邮箱
# EMAIL_PORT = 465     #发件箱的SMTP服务器端口
# EMAIL_HOST_USER = '804026502@qq.com'    #发送邮件的邮箱地址
# EMAIL_HOST_PASSWORD = 'uvaclefjobdgbajj'         #发送邮件的邮箱密码(这里使用的是授权码)

# 支付宝目录路径设置
ying_yong_si_yao = os.path.join(BASE_DIR, 'app1/alipay/ying_yong_si_yao.txt')
zhi_fu_bao_gong_yao = os.path.join(BASE_DIR, 'app1/alipay/zhi_fu_bao_gong_yao.txt')