# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phonenum',
            field=models.CharField(max_length=12, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_name',
            field=models.CharField(db_index=True, max_length=80, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_position',
            field=models.CharField(max_length=128, verbose_name='商品所在地'),
        ),
    ]
