# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190509_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, help_text='选择用户类型的编号', verbose_name='性别'),
        ),
    ]
