# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190509_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, help_text='请选择性别', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_avatar',
            field=models.ImageField(null=True, upload_to='static/upload/avatar', verbose_name='头像'),
        ),
    ]
