# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-11 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190510_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_avatar',
            field=models.ImageField(null=True, storage=system.storage.ImageStorage(), upload_to='static/upload/avatar', verbose_name='头像'),
        ),
    ]
