# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_place',
            field=models.CharField(max_length=64, null=True, verbose_name='居住地'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='com_isactive',
            field=models.BooleanField(default=False, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='static/upload/picture', verbose_name='商品照片'),
        ),
    ]
