# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_commodity_com_issold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=12, null=True, verbose_name='收件人手机'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.CharField(max_length=16, null=True, verbose_name='收件人'),
        ),
    ]
